### ISSUE TITLE
Docker run Jibri error

### ISSUE THREAD

**Issue by marcoadasilvaa** [netaskd/docker-jitsi-meet#1]
Hi, thanks for contributing jibri. I'm trying to run Jibri only local docker to implement it in kurbenetes, but it generates the following error:

````
marcodasilva@LAPTOP-MADSA01:~/docker-jitsi-meet/jibri$ docker run -it --device /dev/snd --device /dev/dri -v /dev/shm:/dev/shm 1053f1e5a502
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-set-timezone: executing... 
[cont-init.d] 01-set-timezone: exited 0.
[cont-init.d] 10-config: executing... 
ERROR: Please set DISPLAY variable.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
ERROR: Please load snd-aloop module on the docker host.
stat: cannot stat '/dev/snd/pcmC0D0p': No such file or directory
Usage: usermod [options] LOGIN

Options:
  -c, --comment COMMENT         new value of the GECOS field
  -d, --home HOME_DIR           new home directory for the user account
  -e, --expiredate EXPIRE_DATE  set account expiration date to EXPIRE_DATE
  -f, --inactive INACTIVE       set password inactive after expiration
                                to INACTIVE
  -g, --gid GROUP               force use GROUP as new primary group
  -G, --groups GROUPS           new list of supplementary GROUPS
  -a, --append                  append the user to the supplemental GROUPS
                                mentioned by the -G option without removing
                                him/her from other groups
  -h, --help                    display this help message and exit
  -l, --login NEW_LOGIN         new value of the login name
  -L, --lock                    lock the user account
  -m, --move-home               move contents of the home directory to the
                                new location (use only with -d)
  -o, --non-unique              allow using duplicate (non-unique) UID
  -p, --password PASSWORD       use encrypted password for the new password
  -R, --root CHROOT_DIR         directory to chroot into
  -s, --shell SHELL             new login shell for the user account
  -u, --uid UID                 new UID for the user account
  -U, --unlock                  unlock the user account
  -v, --add-subuids FIRST-LAST  add range of subordinate uids
  -V, --del-subuids FIRST-LAST  remove range of subordinate uids
  -w, --add-subgids FIRST-LAST  add range of subordinate gids
  -W, --del-subgids FIRST-LAST  remove range of subordinate gids
  -Z, --selinux-user SEUSER     new SELinux user mapping for the user account

[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
````

**Comment by netaskd** [comment]
Hi @marcoadasilvaa ,
It means that you didn't setup node for using loopback interfaces. please read
https://github.com/netaskd/docker-jitsi-meet#jitsi-broadcasting-infrastructure-configuration
Also you have to set DISPLAY variable. usually it "DISPLAY=:0"

**Comment by marcoadasilvaa** [comment]
Thanx!

Investigating on the subject, jitsi/base-java is Debian 9 and this version don't have support for snd_aloop or module alsa.

I have active jibri service active on Ubuntu 16 server but i can't update service because next version of kernel have deprecate aloop module.

Please can't you share version of a SO and Kernel and i contributed for update and fix for this problem.

**Comment by netaskd** [comment]
As a host I use Centos7 x64 kernel 3.10.0-957.21.3.el7.x86_64 for this purpose. I did run it on Ubuntu 16 and it worked perfect.

You don't need make support snd_aloop inside jibri container. It must be loaded on the host where docker daemon is run. 

When you start application from `jibri.yml` file, the argument
```
...
 devices:
            - /dev/snd:/dev/snd
...
```
will bind /dev/snd from the host to the container. 

From the point of view jibri conatainer, it just a r/w files inside /dev/snd that the jibri application uses for r/w media.

note: the kernel inside a container is the same as host's.

**Comment by aesnguyen** [comment]
Hi @netaskd, I got this error when I tried to build jibri docker in pr_jibri2 branch. Can You give me some advance? Thanks
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.web.environment contains non-unique items, please remove duplicates from ['ENABLE_AUTH', 'ENABLE_GUESTS', 'ENABLE_LETSENCRYPT', 'ENABLE_HTTP_REDIRECT', 'ENABLE_TRANSCRIPTIONS', 'DISABLE_HTTPS', 'ENABLE_RECORDING', 'JICOFO_AUTH_USER', 'LETSENCRYPT_DOMAIN', 'LETSENCRYPT_EMAIL', 'PUBLIC_URL', 'XMPP_DOMAIN', 'XMPP_AUTH_DOMAIN', 'XMPP_BOSH_URL_BASE', 'XMPP_GUEST_DOMAIN', 'XMPP_MUC_DOMAIN', 'XMPP_RECORDER_DOMAIN', 'ETHERPAD_URL_BASE', 'TZ', 'JIBRI_BREWERY_MUC', 'JIBRI_PENDING_TIMEOUT', 'JIBRI_XMPP_USER', 'JIBRI_XMPP_PASSWORD', 'JIBRI_RECORDER_USER', 'JIBRI_RECORDER_PASSWORD', 'ENABLE_RECORDING']
