### ISSUE TITLE
If TURN is activated with ports 10000-11000, how to set JVB_PORT in .env?

### ISSUE THREAD

**Issue by pandel** [netaskd/docker-jitsi-meet#2]
Hi!

I'd really like to try your TURN server modification. When I configure .env as stated in the example, I get an error when the videobridge is startet, that port 10000 is already in use. I understand that if I use ports 10000-11000 for TURN that setting JVB_PORT to 10000 is not possible.

But what should I do? Set JVB_PORT to 9999 or TURN port range to 10001-11000?

Hope you can help?

Many thanks and keep up the good work!

Regards,
Holger

**Comment by netaskd** [comment]
Hi Holger,
You are free to use any ports what you want ) Just remember that ports have not be crossed. And, of cource, it must be allowed on your in-firewall.
Example of usage:
Jvb port: 10k/udp
Turn ports: 16k-17k/udp
________________________________

**Comment by pandel** [comment]
Hi!

Thanks. I know that ports should not cross :-) - that's why I asked, because your env.example does not take that into account and I wasn't sure, i there is any special setting I overlooked.

I'll give it a try.
Regards
Holger

**Comment by netaskd** [comment]
I've changed an example in aa52b36
